app/urls.py
from django.conf.urls import url

from app import views

urlpatterns=[
    url(r'^hello/',views.hello,name='hello'),
    # url(r'^register/',views.register,name='register'),
    url(r'^register/',views.RegisterView.as_view(),name='register'),
    url(r'^login/',views._login,name='login'),
    url(r'^imgcode/',views.ImageCodeView.as_view(),name='imgcode'),
    url(r'^index/',views.index,name='index'),
]

blogTest/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include

#日志器的使用步骤
#1.导入logging包
import logging

#获取日志器
logger=logging.getLogger('djangoLog')
def log(request):
    #3.使用日志器记录信息
    logger.info('危险!!!') #信息内容由自己确定
    return HttpResponse('The test for logging.')



urlpatterns = [
    path('admin/', admin.site.urls),
    # url(r'^app/',include(('app.urls','aaa'),namespace='aaa')),
    url('',include(('app.urls','aaa'),namespace='aaa')),
    url('',include(('home.urls','aaa'),namespace='home')),
    # url('',log),
]

home/urls.py
from django.conf.urls import url

from home import views
from app import views as appviews
from home.views import UserCenterView, writeBlogView

urlpatterns=[
    
    url(r'^home/',views.home,name='home'), #用户中心
    url(r'^logout/',views._logout,name='logout'), #退出
    url(r'^login/',appviews._login,name='login'), #登录
    url(r'^usercenter/',UserCenterView.as_view(),name='usercenter'), #用户中心(副本)
    url(r'^caogao/', views.caogao, name='caogao'), #草稿(用于测试)
    url(r'^index/', appviews.index, name='index'), #主页
    url(r'^writeBlog/',writeBlogView.as_view(),name='writeBlog'),#写博客

]

home/models.py
from django.db import models
from django.utils import timezone
from app.models import User

#博客类别
class ArticleCategory(models.Model):
    '''文章分类'''

    # 标题
    title = models.CharField(max_length=100, blank=True, db_column='标题')
    # 创建时间
    createdTime = models.DateTimeField(auto_now=True, db_column='创建时间')

    # admin站点显示,调查查看对象方便
    def __str__(self):
        return self.title

    class Meta:
        db_table = '文章分类'  # 修改表名
        verbose_name = '类别管理'  # admin站点显示
        verbose_name_plural = verbose_name

#博客
class Article(models.Model):
    # 作者
    author = models.ForeignKey(User, on_delete=models.CASCADE, db_column='作者')

    # 标题
    title = models.CharField(max_length=20, blank=True, db_column='标题')

    # 分类
    category = models.ForeignKey(ArticleCategory, on_delete=models.CASCADE, db_column='分类')

    # 标签
    tags = models.CharField(max_length=50, blank=True, db_column='标签')

    # 摘要信息
    summary = models.CharField(max_length=200, null=False, blank=False, db_column='摘要信息')

    # 文章正文
    content = models.TextField(db_column='文章正文')

    # 浏览量
    total_views = models.PositiveIntegerField(default=0, db_column='浏览量')

    #获赞量
    total_likes=models.PositiveIntegerField(default=0,db_column='获赞量')

    # 不喜欢量
    total_nolikes = models.PositiveIntegerField(default=0, db_column='不喜欢量')

    # 评论量
    comments_count = models.PositiveIntegerField(default=0, db_column='评论量')

    # 文章创建时间
    createdTime = models.DateTimeField(default=timezone.now, db_column='文章创建时间')

    # 文章修改的时间
    updatedTime = models.DateTimeField(auto_now=True, db_column='文章修改的时间')  # 自动添加

    # 标题图 该图用于大厅页的展示 做多9张 9宫格
    avatar1 = models.ImageField(upload_to='static/article/%Y%m%d/', blank=True, db_column='标题图1')
    avatar2 = models.ImageField(upload_to='static/article/%Y%m%d/',null=True, blank=True, db_column='标题图2')
    avatar3 = models.ImageField(upload_to='static/article/%Y%m%d/',null=True, blank=True, db_column='标题图3')
    avatar4 = models.ImageField(upload_to='static/article/%Y%m%d/',null=True, blank=True, db_column='标题图4')
    avatar5 = models.ImageField(upload_to='static/article/%Y%m%d/',null=True, blank=True, db_column='标题图5')
    avatar6 = models.ImageField(upload_to='static/article/%Y%m%d/',null=True, blank=True, db_column='标题图6')
    avatar7 = models.ImageField(upload_to='static/article/%Y%m%d/',null=True, blank=True, db_column='标题图7')
    avatar8 = models.ImageField(upload_to='static/article/%Y%m%d/',null=True, blank=True, db_column='标题图8')
    avatar9 = models.ImageField(upload_to='static/article/%Y%m%d/',null=True, blank=True, db_column='标题图9')

    class Meta:
        db_table='博客' #修改表名
        ordering=('-createdTime',) #按照创建时间进行排序
        verbose_name='文章管理'
        verbose_name_plural=verbose_name

    def  __str__(self):

        return self.title

home/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from django.urls import reverse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from app.models import User

#用户中心 继承django内置的LoginRequiredMixin类 用于判断用户是否处于登录状态
class UserCenterView(View,LoginRequiredMixin):
    def get(self,request):
        #获得用户的相关信息
        user=request.user
        print(3333,user.username)
        return render(request,'home.html')




#个人中心
def home(request):
    username = request.COOKIES.get('username')
    if username==None: #只有登录之后的用户才能访问该页面
        return redirect(reverse('aaa:login'))

    # 通过数据上传
    if request.method=='GET':
        avatar=''
        try:
            user=request.user
            avatar=user.avatar
        except:return redirect(reverse('aaa:login'))
        #如果用户没有上传头像,使用系统默认头像
        if not avatar:
            avatar='imgs/test.jpg'

        context={
            'avatar':str(avatar).replace('static/','')

        }
        return render(request, 'home.html',context=context)

    #修改图像
    if request.method=='POST':
        imgfile = request.FILES.get('imgfile')
        img = User.objects.filter(username=username).first()
        img.avatar = imgfile
        img.save()
        return HttpResponse('文件上传成功!')

#退出登录
def _logout(request):
    #调用系统内置的退出登录方法 删除session数据
    logout(request)
    #删除cookie数据
    response=redirect(reverse('home:home'))
    response.delete_cookie('is_login')
    response.delete_cookie('username')
    return response


#用于测试
def caogao(request):
    return render(request,'caogao.html')


#写博客
class writeBlogView(View,LoginRequiredMixin):

    def get(self,request):
        isLogin=request.COOKIES.get('is_login')
        username=request.COOKIES.get('username')
        print(username,isLogin)
        if not isLogin or not username: #如果没有登录的话就先登录
            return redirect(reverse('home:login'))

        avatar=User.objects.filter(username=username).first().avatar
        return render(request,'writeBlog.html',context={'avatar':str(avatar).replace('static/','')})



    def post(self,request):
        return

templates/blogModel.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>


   <style>

        figure.image {
            display: inline-block;
            border: 1px solid gray;
            margin: 0 2px 0 1px;
            background: #f5f2f0;
        }

        figure.align-left {
            float: left;
        }

        figure.align-right {
            float: right;
        }

        figure.image img {
            margin: 8px 8px 0 8px;
        }

        figure.image figcaption {
            margin: 6px 8px 6px 8px;
            text-align: center;
        }


        /*
         Alignment using classes rather than inline styles
         check out the "formats" option
        */

        img.align-left {
            float: left;
        }

        img.align-right {
            float: right;
        }

        /* Basic styles for Table of Contents plugin (toc) */
        .mce-toc {
            border: 1px solid gray;
        }

        .mce-toc h2 {
            margin: 4px;
        }

        .mce-toc li {
            list-style-type: none;
        }


    </style>
    <script src="../static/js/tinymce.js"></script>
    <form action="#">
<textarea id="full-featured-non-premium">
</textarea>
    </form>
</body>
</html>

templates/caogao.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<input type="file" id="file"  multiple="multiple" onchange="read()">
<div id="imgDiv"></div>
</body>
<script>
    //可以选择多个文件加载在页面
   function read(){
        var file = document.getElementById("file");
        var imgDiv = document.getElementById("imgDiv");
        for(var i=0;i<file.files.length;i++){
            let reader = new FileReader();
            var file1 = file.files[i];
            reader.readAsDataURL (file1);
            reader.onload = function (result) {
                //reader对象的result属性存储流读取的数据
                imgDiv.innerHTML += '<img src="' + reader.result + '" alt=""/>'

            }
        }
    }
</script>
</html>

templates/footer.html
{% comment %}版权{% endcomment %}
<div style="width:100%;height:50px;line-height:50px;background-color:#8080802b; display:inline-block; text-align:center">
        Copyrights©2021 Vaccine Inquiry All Rights Reserved. Email: 2474605919@qq.com</div>

</div>

templates/head.html
{% load static %}
<style>
    #head, #content, #footer {
        width: 100%;

    }

    {% comment %}头部样式{% endcomment %}

    #head {
        height: 200px;
        border-bottom: 1px solid gray;
        background-color: #e0eaff;
    }

    #head-le, #head-mid, #head-ri {
        float: left;
    }

    #head-le {
        width: 25%;
    {% comment %}360px{% endcomment %} height: 100%;
    {% comment %}200px{% endcomment %} text-align: center;
        font-size: 50px;

    }

    #head-le-bottom, #head-le-top {
        width: 100%;
    {% comment %}360px{% endcomment %} height: 50%;
    {% comment %}100px{% endcomment %} float: left;
        line-height: 50px;
    }

    #head-le-top {
        line-height: 160px;
        border-bottom: 5px solid green;

    }

    #head-le-bottom span:first-child {
        text-shadow: 1px 1px 1px #000, -1px -1px 1px #fff; /*凸起的文字*/
        color: rgb(33, 212, 134);
    }

    #head-le-bottom strong {
        text-shadow: -1px -1px 1px #000, 1px 1px 1px #fff; /*凹陷的文字*/
        color: #3b7ca7;
    }

    #head-le-bottom i {
        color: #ffb22f;
    }

    #head-mid {
        width: 60%;
        height: 100%;
    }

    #head-mid-top form {
        padding: 0;
        width: 30%;
        height: 40%;
        border: 1px solid black;
        border-radius: 15px;
        overflow: hidden;
        float: right;
        margin-right: 120px;
        margin-top: 15px;
        box-sizing: border-box;
        background-color: black;
        position: relative;


    }

    #head-mid-top form input:first-child {
        width: 70%;
        height: 100%;
        border: none;
        box-sizing: border-box;
        border-radius: 0;

    }

    #head-mid-top form input:last-child {
        width: 29%;
        height: 100%;
        border: none;
        background-color: #fff;
        float: right;
        position: absolute;
        right: 0;
        top: 0;
        box-sizing: border-box;
        border-radius: 0;
    }


    #head-mid-bottom ul {
        width: 100%;
        height: 100%;
    }

    #head-mid-bottom ul li {
        float: left;
        width: 20%;
        height: 100%;
        text-align: center;
        line-height: 100px;
        transition: all .5s linear;
    }

    #head-mid-bottom ul li:hover {
        background-color: #fff;
        font-size: 15px;
    }

    #head-ri {
        width: 15%;
        height: 100%;
    }


    #head-le-top, #head-mid-top, #head-ri-top {
        border-bottom: 5px solid green;
        width: 100%;
        height: 50%;
        float: left;

    }

    #head-le-bottom, #head-mid-bottom, #head-ri-bottom {

        width: 100%;
        height: 50%;
        float: left;

    }

    #head-ri-bottom {
        text-align: center;
        padding-top: 20px;
        width: 100%;
        height: 99.5px;


    }

    #avatar {
        position: relative;
        display: block;
        width: 50px;
        height: 50px;
        overflow: hidden;
        background-color: #fff;
        left: 100px;
        top: 10px;

    }

    #avatar img {
        position: absolute;
        width: 110%;
        height: 110%;
        border: 2px solid gray;
        left: -2px;
        top: -2px;

    }

    #blockAvatar {
        width: 100%;
        height: 100%;
        position: absolute;
        left: 0;
        background-color: rgba(0, 0, 0, .4);
        font-size: 10px;
        line-height: 50px;
        font-weight: 600;
    }


</style>
<script>
    window.onload = function () {

        {% comment %}判断用户是否登录{% endcomment %}
        var username = getCookie('username');
        var headRiBottom = document.getElementById('head-ri-bottom');
        if (!username) {
            headRiBottom.innerHTML = `<a href="{% url 'aaa:login' %}"><span class="iconfont" style="font-size:20px;">&#xe62a;请先登录</span></a>`;
        } else {
            headRiBottom.innerHTML = `<a id="avatar" href="{% url 'home:home' %}" class="img-circle">
                <img  src="{% static ''%}{{ avatar }}"><span id="blockAvatar">个人中心</span></a>`;
        }


        var keyword = document.getElementById('keyword');
        var spanNextInput = document.getElementById('spanNextInput');
        var tipSpan = document.getElementById('tipSpan');

        spanNextInput.onmousemove = function () {
            tipSpan.innerHTML = '来打我呀!??';
        }
        spanNextInput.onmouseout = function () {
            tipSpan.innerHTML = '';
        }

        {% comment %}输入框聚焦时宽度变长{% endcomment %}
        keyword.onfocus = function () {
            let formTag = keyword.parentNode;
            perfectMove(formTag, {
                width: 512,
            }, function () {
                let spanNextInput = document.getElementById('spanNextInput');
                spanNextInput.style.color = 'green';
                tipSpan.style.display = 'inline';
                tipSpan.style.position = 'absolute';
                tipSpan.innerHTML = '你撞到我头了!';
            })
        }

        keyword.onblur = function () {
            let formTag = keyword.parentNode;
            perfectMove(formTag, {
                width: 200,
            }, function () {
                let spanNextInput = document.getElementById('spanNextInput');
                spanNextInput.style.color = 'skyblue';
                tipSpan.innerHTML = '下次小心一点!!!';
                setTimeout(function () {
                    tipSpan.innerHTML = '';
                }, 1000);

            })
        }

        {% comment %}经过头像显示个人中心{% endcomment %}
        var blockAvatar = document.getElementById('blockAvatar');
        blockAvatar.style.display = 'none';
        var avatar = document.getElementById('avatar');
        avatar.onmousemove = function () {
            blockAvatar.style.display = 'block';

        }
        avatar.onmouseleave = function () {
            blockAvatar.style.display = 'none';
        }


        {% comment %}写博客界面{% endcomment %}
        //选择标签
        var tagsFrame = document.getElementById('tagsFrame');
        var spanList = tagsFrame.getElementsByTagName('span');
        tagsFrame.onclick = function (ev) {
            var e = ev || window.event;
            var target = e.target || window.event.srcElement; //找到目标对象

            if (target.nodeName.toLowerCase() === 'span' && target.className === 'noSeleected') {
                target.className = 'seleected';
            } else if (target.nodeName.toLowerCase() === 'span' && target.className === 'seleected') {
                target.className = 'noSeleected';
            } else if (target.nodeName.toLowerCase()==='label') {
            } else if(target.className){
               let newTag= prompt('请输入要添加的标签名:');
                let newSpan=document.createElement('span');
                newSpan.className = 'seleected';
                newSpan.innerHTML=newTag;
                tagsFrame.appendChild(newSpan);


            }


        }


    }
</script>
<div id="head">
    <div id="head-le">

        <div id="head-le-top">
            <svg style="font-size:40px;color:#3b7ca7;" class="icon" aria-hidden="true">
                <use xlink:href="#icon-gouxiao"></use>
            </svg>
            <span class="iconfont" style="font-size:50px;color:skyblue;width:50px;height:50px;text-align: right">&#xe616;</span>
            <svg style="font-size:40px;color:#3b7ca7;" class="icon" aria-hidden="true">
                <use xlink:href="#icon-yepian"></use>
            </svg>
            <svg style="font-size:100px;" class="icon" aria-hidden="true">
                <use xlink:href="#icon-gouwo"></use>
            </svg>

        </div>

        <div id="head-le-bottom">
            <span>狗</span>
            <strong>狗</strong>
            <svg style="font-size:30px;" class="icon" aria-hidden="true">
                <use xlink:href="#icon-gou12"></use>
            </svg>
            <i><u>部落</u></i>
        </div>

    </div>

    <div id="head-mid">
        <div id="head-mid-top">
            <span id="spanNextInput" class="iconfont" style="font-size:50px;color:skyblue;">&#xe60d;</span>

            <span id="tipSpan"></span>
            <form class="form-inline" action="#" target="_blank">
                <input autocomplete="off" type="text" class="form-control" required="required" name="keyword"
                       placeholder="Search" id="keyword">
                <input type="submit" class="button" value="搜索">
            </form>
        </div>
        <div id="head-mid-bottom">
            <ul>
                <li><a href="{% url 'home:index' %}"><span class="iconfont"
                                                           style="font-size:30px;">&#xe60f;</span>大厅</a></li>
                <li><a href="#"><span class="iconfont" style="font-size:30px;">&#xe737;</span>狗窝</a></li>
                <li><a href="#"><span class="iconfont" style="font-size:30px;">&#xe60d;</span>狗狗大全</a></li>
                <li><a href="#"><span class="iconfont" style="font-size:30px;">&#xe608;</span>狗狗护理</a></li>
                <li><a href="{% url 'home:writeBlog' %}"><span class="iconfont" style="font-size:30px;">&#xe84a;</span>狗狗日记</a>
                </li>
            </ul>


        </div>


    </div>
    <div id="head-ri">
        <div id="head-ri-top">
            <span class="iconfont" style="font-size:30px;color:skyblue;height:100px;">&#xe615;</span>
            <span class="iconfont" style="font-size:30px;color:skyblue;height:100px;">&#xe60b;</span>
            <span class="iconfont" style="font-size:15px;color:skyblue;height:100px;">&#xe612;</span>
            <span class="iconfont" style="font-size:80px;color:skyblue;height:100px;">&#xe629;</span>
        </div>
        <div id="head-ri-bottom">


        </div>

    </div>
</div>

templates/login.html
{% comment %}加载静态文件{% endcomment %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>register</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <style>
        body {
            background-color: rgba(78, 115, 223, 0.8);
        }

        * {
            padding: 0;
            margin: 0;
        }

        .container {
            border: 1px solid black;
            width: 800px;
            padding: 0;
            margin: 50px auto;
            border-radius: 15px;
            overflow: hidden;
        }

        #con {
            width: 100%;
            height: 500px;
        }

        #con-le, #con-ri {
            width: 50%;
            height: 100%;
            float: left;
        }

        #con-le {
            background: url('{% static "imgs/register.jpg" %}');
            background-repeat: no-repeat;
            background-size: 100% 100%;
        }

        .conMed {
            width: 80%;
            height: 15%;
            margin: 5% auto;
        {#border: 1px solid black;#} line-height: 60px;
        }

        .conMed input {
            float: right;
            height: 60%;
            margin-top: 12px;
        }

        form {
            width: 100%;
            height: 100%;
            background-color: #fff;
            text-align: center;
            padding-top: 5%;
        }

        #verifyCode {
            float: left;
            width: 35%;
            height: 100%;
            border: 1px solid black;
        }

        #button {
            width: 100%;
            height: 100%;

        }

    </style>

</head>
<body>

<div class="container">


    <div id="con">

        <div id="con-le"></div>
        <div id="con-ri">
            <form action="{% url 'aaa:login' %}" class="form-group form-inline" method="post">

                <h3 style="margin: 0;border-bottom:1px solid gray">欢迎回来!</h3>
                <div class="conMed"><label for="">账&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号:</label>
                    <input type="text" value="{{ account }}" class="form-control" name="account" required minlength="6">
                </div>
                <div class="conMed"><label for="">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码:</label>
                    <input value="" class="form-control" name="password" type="password" required></div>
                <div class="conMed" style="height:10%;line-height:50px;">
                    <div id="button" style="font-size:18px;"><input class="button btn-info" type="submit"
                                                                    value="登&nbsp;&nbsp;录"
                                                                    style="width:100%;height:100%"></div>
                </div>
                <hr>
                <hr>
                <div class="conMed">
                    <a href="{% url 'aaa:register' %}">还没有账号?注册!</a>
                </div>
            </form>
        </div>


    </div>


</div>



</body>

templates/register.html
{% comment %}加载静态文件{% endcomment %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>register</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <style>
        body {
            background-color: rgba(78, 115, 223, 0.8);
        }

        * {
            padding: 0;
            margin: 0;
        }

        .container {
            border: 1px solid black;
            width: 800px;
            padding: 0;
            margin: 50px auto;
            border-radius: 15px;
            overflow: hidden;
        }

        #con {
            width: 800px;
            height: 600px;
        }

        #con-le, #con-ri {
            width: 400px;
            height: 600px;
            float: left;
        }

        #con-le {
            background: url('{% static "imgs/login.jpg" %}');
            background-repeat: no-repeat;
            background-size: 100% 100%;
        }

        .conMed {
            width: 320px;
            height: 60px;
            margin: 5% auto;
            line-height: 60px;
        }

        .conMed input {
            float: right;
            height: 36px;
            width: 200px;
            margin-top: 12px;
        }
        .conMed label {
        float: left;
        }

        form {
            width: 100%;
            height: 100%;
            background-color: #fff;
            text-align: center;
            padding-top: 5%;
            display: block;
        }

        #verifyCode {
            float: left;
            width: 35%;
            height: 100%;
            border: 1px solid black;
            overflow: hidden;
        }


    </style>
    <script src="{% static 'js/tools.js' %}"></script>

    <script>

        window.onload = function () {
            {% comment %}点击更新验证码{% endcomment %}
            var verifyCodeOut = document.getElementById('verifyCode');

            function updateVerifyCode() {
                let date = new Date();
                let timestamp = date.getTime();//http://10.181.211.109:8000/imgcode/
                verifyCodeOut.innerHTML = `<img src="{% url 'aaa:imgcode' %}/${timestamp}" style="width:100%;height:100%;">`;
            }

            verifyCodeOut.onclick = function () {
                updateVerifyCode();
            }

            {% comment %}点击提交表单{% endcomment %}
            var inputList = document.getElementsByTagName('input');
            var tipsList = document.getElementsByClassName('tips');
            var account = inputList[0];
            var password = inputList[1];
            var confirmPassword = inputList[2];
            var verifyCode = inputList[3];
            var accountTip = tipsList[0];
            var passwordTip = tipsList[1];
            var confirmPasswordTip = tipsList[2];
            var accountOk = 0;
            var passwordOk = 0;
            var confirmPasswordOk = 0;

            {% comment %}判断账号的格式是否满足{% endcomment %}
            account.onblur = function () {
                accountValue = account.value;
                if (accountValue.length < 6 || accountValue.length > 11) {
                    accountTip.innerHTML = `<span class="glyphicon glyphicon-remove" style="color:red;"></span>`;
                    accountOk = 0;
                } else {
                    accountTip.innerHTML = `<span class="glyphicon glyphicon-ok" style="color:green;display: inline-block;  "></span> `;
                    accountOk = 1;
                }
            }

            {% comment %}判断密码的格式是否满足{% endcomment %}

            function passwordOnblur() {
                passwordValue = password.value;
                if (!/[a-zA-Z]/.test(passwordValue) || !/[0-9]/.test(passwordValue)) {
                    passwordTip.innerHTML = `<span class="glyphicon glyphicon-remove" style="color:red;"></span>`;
                    passwordOk = 0;
                } else {
                    passwordTip.innerHTML = `<span class="glyphicon glyphicon-ok" style="color:green;display: inline-block;  "></span> `;
                    passwordOk = 1;
                }
            }

            password.onblur = function () {
                passwordOnblur();
                confirmPasswordOnblur();
            }

            {% comment %}确认密码{% endcomment %}

            function confirmPasswordOnblur() {
                passwordValue = password.value;
                confirmPasswordValue = confirmPassword.value;
                if (passwordValue !== confirmPasswordValue || confirmPasswordValue.length<6 || !/[a-zA-Z]/.test(confirmPasswordValue) || !/[0-9]/.test(confirmPasswordValue)) {
                    confirmPasswordTip.innerHTML = `<span class="glyphicon glyphicon-remove" style="color:red;"></span>`;
                    confirmPasswordOk = 0;
                } else {
                    confirmPasswordTip.innerHTML = `<span class="glyphicon glyphicon-ok" style="color:green;display: inline-block;  "></span> `;
                    confirmPasswordOk = 1;
                }
            }

            confirmPassword.onblur = function () {
                confirmPasswordOnblur();
            }

            var button = document.getElementById('submit');

            function buttonClick() {
                if (!accountOk || !passwordOk || !confirmPasswordOk) {
                    alert('请检查表单!');
                } else {
                    $ajax('post', ' {% url "aaa:register" %}', {
                            'account': account.value,
                            'password': password.value,
                            'confirmPassword': confirmPassword.value,
                            'verifyCode': verifyCode.value
                        },
                        function (msg) {
                            let data = JSON.parse(msg)['msg'];
                            alert(data);
                        },
                        function (msg) {
                            let data = JSON.parse(msg)['msg'];

                            alert('失败' + data);
                        },
                    )


                }
                updateVerifyCode();

            }

            {% comment %}为按钮添加点击事件{% endcomment %}
            button.addEventListener('click', buttonClick, false);


        }


    </script>

</head>
<body>

<div class="container">


    <div id="con">

        <div id="con-le"></div>
        <div id="con-ri">
            <form action="#" class="form-group form-inline" method="post">
                {% comment %}{% csrf_token %}{% endcomment %}
                <h3 style="margin: 0;border-bottom:1px solid gray">创建账号!</h3>


                <div class="conMed"><label for="">账&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;号:</label>
                    <input type="text" value="" class="form-control" name="account" placeholder="6~11位字符">
                    <div style="float:right;width:15%;height:100%;" class="tips"></div>

                </div>
                <div class="conMed"><label for="">密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码:</label>
                    <input type="password" value="" class="form-control" name="password" placeholder="至少包含数字和字母">
                    <div style="float:right;width:15%;height:100%;" class="tips"></div>

                </div>

                <div class="conMed"><label for="">确认密码:</label>
                    <input type="password" value="" class="form-control" name="confirmPassword" placeholder="同上输入保持一致">
                    <div style="float:right;width:15%;height:100%;" class="tips"></div>

                </div>
                <div class="conMed">
                    <div id="verifyCode"><img src="{% url 'aaa:imgcode' %}" style="width:100%;height:100%;"></div>
                    <input class="form-control" type="text" placeholder="请输入验证码" id="verifyInput" name="verifyCode">
                </div>
                <div class="conMed">
                    <div type="submit" class="button btn-info" id="submit" style="font-size:18px;">注&nbsp;册</div>

                </div>
                <hr>
                <hr>
                <div class="conMed">
                    <a href="{% url 'aaa:login' %}">已有账号!登录!</a>
                </div>


            </form>
        </div>


    </div>


</div>


</body>
</html>